apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-event-portal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-event-portal
  template:
    metadata:
      labels:
        app: smart-event-portal
    spec:
      containers:
      - name: smart-event-portal
        image: kartik12325401/smart-event-portal:v2
        ports:
        - containerPort: 3000
