apiVersion: v1
kind: Service

metadata:
  name: smart-event-portal-service

spec:
  selector:
    app: smart-event-portal

  type: NodePort

  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080